import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar untuk Aerplus Kasir
  aerplusKasirSidebar: [
    {
      type: 'autogenerated',
      dirName: 'aerplus-kasir',
    },
  ],

  // Sidebar untuk Aerplus Admin
  aerplusAdminSidebar: [
    {
      type: 'autogenerated',
      dirName: 'aerplus-admin',
    },
  ],

  // Sidebar untuk Aerplus Supplier
  aerplusSupplierSidebar: [
    {
      type: 'autogenerated',
      dirName: 'aerplus-supplier',
    },
  ],

  // Sidebar untuk Toko Kita
  tokoKitaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'toko-kita',
    },
  ],

  // Default sidebar untuk konten lainnya
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
